name: Elixir CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.12.3"
            otp: "24.3.4.17"

          # Modern Elixir w/ modern OTP
          - elixir: "1.18.4"
            otp: "28.0"

    env:
      MIX_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up BEAM
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          install-hex: true
          install-rebar: true

      - name: Cache deps and build
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
            ~/.mix
          key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-

      - name: Deps
        run: mix deps.get --only $MIX_ENV

      - name: Compile
        run: mix compile

      - name: Test
        run: mix test --color
